exclude: quick_client
repos:
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [ '--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports' ]

  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements

  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.990'
    hooks:
      - id: mypy
        # required because pre-commit uses separate venv
        # use poetry show to get exact versions
        additional_dependencies: [types-PyYAML==5.4.7,types-setuptools==57.0.2]
