# coding: utf-8

"""
    Quick Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import quick_client
from quick_client.api.default_api import DefaultApi  # noqa: E501
from quick_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = quick_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_gateway(self):
        """Test case for create_gateway

        Creates a new gateway  # noqa: E501
        """
        pass

    def test_create_mirror(self):
        """Test case for create_mirror

        Creates a mirror for a topic  # noqa: E501
        """
        pass

    def test_create_new_topic(self):
        """Test case for create_new_topic

        Creates a new topic  # noqa: E501
        """
        pass

    def test_create_schema(self):
        """Test case for create_schema

        Creates a new GraphQL schema  # noqa: E501
        """
        pass

    def test_delete_application(self):
        """Test case for delete_application

        Deletes an application  # noqa: E501
        """
        pass

    def test_delete_gateway(self):
        """Test case for delete_gateway

        Deletes a gateway  # noqa: E501
        """
        pass

    def test_delete_mirror(self):
        """Test case for delete_mirror

        Deletes mirror of topic  # noqa: E501
        """
        pass

    def test_delete_topic(self):
        """Test case for delete_topic

        Deletes topic  # noqa: E501
        """
        pass

    def test_deploy_application(self):
        """Test case for deploy_application

        Deploys a new application  # noqa: E501
        """
        pass

    def test_get_application_information(self):
        """Test case for get_application_information

        Retrieves information about the given application  # noqa: E501
        """
        pass

    def test_get_applications(self):
        """Test case for get_applications

        Retrieves all deployed quick applications  # noqa: E501
        """
        pass

    def test_get_avro_write_schema(self):
        """Test case for get_avro_write_schema

        Returns the Gateway schema in Avro format  # noqa: E501
        """
        pass

    def test_get_gateway(self):
        """Test case for get_gateway

        Retrieves information about a gateway  # noqa: E501
        """
        pass

    def test_get_graphql_write_schema(self):
        """Test case for get_graphql_write_schema

        Returns the Gateway schema in GraphQL format  # noqa: E501
        """
        pass

    def test_get_topic_information(self):
        """Test case for get_topic_information

        Gets information about a topic  # noqa: E501
        """
        pass

    def test_list_all_gateways(self):
        """Test case for list_all_gateways

        List all deployed gateways  # noqa: E501
        """
        pass

    def test_list_all_topics(self):
        """Test case for list_all_topics

        List all registered topic  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
