# coding: utf-8

"""
    Quick Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import quick_client
from quick_client.models.topic_data import TopicData  # noqa: E501
from quick_client.rest import ApiException

class TestTopicData(unittest.TestCase):
    """TopicData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TopicData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = quick_client.models.topic_data.TopicData()  # noqa: E501
        if include_optional :
            return TopicData(
                name = '0', 
                write_type = '0', 
                key_type = '0', 
                value_type = '0', 
                schema = '0'
            )
        else :
            return TopicData(
                name = '0',
                write_type = '0',
                key_type = '0',
                value_type = '0',
        )

    def testTopicData(self):
        """Test TopicData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
