# coding: utf-8

"""
    Quick Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import quick_client
from quick_client.models.application_creation_data import ApplicationCreationData  # noqa: E501
from quick_client.rest import ApiException

class TestApplicationCreationData(unittest.TestCase):
    """ApplicationCreationData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ApplicationCreationData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = quick_client.models.application_creation_data.ApplicationCreationData()  # noqa: E501
        if include_optional :
            return ApplicationCreationData(
                name = '0', 
                registry = '0', 
                image_name = '0', 
                tag = '0', 
                replicas = 56, 
                port = 56, 
                image_pull_secret = '0', 
                arguments = quick_client.models.application_creation_data_arguments.ApplicationCreationData_arguments(
                    key = '0', 
                    value = '0', )
            )
        else :
            return ApplicationCreationData(
                name = '0',
                registry = '0',
                image_name = '0',
                tag = '0',
        )

    def testApplicationCreationData(self):
        """Test ApplicationCreationData"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
