# coding: utf-8

"""
    Quick Manager

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import quick_client
from quick_client.models.error_message import ErrorMessage  # noqa: E501
from quick_client.rest import ApiException

class TestErrorMessage(unittest.TestCase):
    """ErrorMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ErrorMessage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = quick_client.models.error_message.ErrorMessage()  # noqa: E501
        if include_optional :
            return ErrorMessage(
                type = '0', 
                title = '0', 
                code = 56, 
                detail = '0', 
                uri_path = '0'
            )
        else :
            return ErrorMessage(
        )

    def testErrorMessage(self):
        """Test ErrorMessage"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
