name: Test quick-cli

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POETRY_VERSION: "1.0.3"

jobs:
  tests:
    name: ${{ matrix.os }} / ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ Ubuntu, MacOS, Windows ]
        python-version: [ 3.7, 3.8, 3.9 ]
    steps:
      - uses: actions/checkout@v3

      - name: Install Python and set up Poetry
        uses: bakdata/ci-templates/actions/python-setup-poetry@v1.2.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: poetry install

      - name: Run pytest
        shell: bash
        run: poetry run python -m pytest -v tests
