name: Code Quality

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
  push:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
#      - uses: actions/setup-python@v2
#      - uses: pre-commit/action@v2.0.0

      - name: Read changelog config
        id: read-config
        run: |
          CONTENT=$(cat ./.github/changelog-config.json)
          echo "CONTENT<<EOF" >> $GITHUB_OUTPUT
          echo "$CONTENT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        shell: bash

      - name: Print config
        run: echo "${{ steps.read-config.outputs.content }}"
        shell: bash
