name: Code Quality

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"

jobs:
  pre-commit:
    name: Linting
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: pre-commit/action@v2.0.0
