name: Upload Python Package to TestPypi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  POETRY_VERSION: "1.1.12"

jobs:
  tests:
    name: ubuntu / ${{ matrix.python-version }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Python and set up Poetry and bump version with Poetry
        id: bump_version
        uses: bakdata/ci-templates/actions/python-poetry-bump-version@v1.2.0
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
          python-version: ${{ matrix.python-version }}
          release-type: "minor"

      - name: Get distance to this tag
        id: get_distance_to_tag
        run: |
          # Get the distance from HEAD and save it to the distance variable
          echo "::set-output name=distance::$(git rev-list HEAD --count)"
        shell: bash

      - name: Set version with poetry
        id: set_poetry_version
        run: |
          # Update the pyproject.toml version. Versioning format for dev packages: X.Y.Z.devN
          # For more information visit: https://www.python.org/dev/peps/pep-0440/#semantic-versioning
          echo "bumped version is ${{ steps.bump_version.outputs.release-tag }}"
          echo "dev version is ${{ steps.get_distance_to_tag.outputs.distance }}"
          echo "end version is ${{ steps.bump_version.outputs.release-tag }}.dev${{ steps.get_distance_to_tag.outputs.distance }}"
          poetry version ${{ steps.bump_version.outputs.release-tag }}.dev${{ steps.get_distance_to_tag.outputs.distance }}
        shell: bash

#      - name: Build and Publish package to TestPyPI
#        run: |
#          # set the repository to TestPyPI
#          poetry config repositories.testpypi https://test.pypi.org/legacy/
#          # first build the project then publish to TestPyPI
#          poetry publish --build --repository testpypi --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }}
#        shell: bash
